"""A generic script template for Alembic."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abb94c05dff'
down_revision = '9509a1a430b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('bus_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'routes', 'buses', ['bus_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_column('routes', 'bus_id')
    # ### end Alembic commands ###
