"""A generic script template for Alembic."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9509a1a430b2'
down_revision = '9ca711a6a171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_route',
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_route')
    # ### end Alembic commands ###
